### PR TITLE
Updated the isprime function to reduce the runtime

### PR DESCRIPTION
**Pull request by PratyayDhond**
x/2 is used to detect if the number is prime
  if the number has no complete divisors till it's half (x/2), then no number after it's half would be a divisor.

e.g. 

x = 29
if 29 is not divible by 14 (29/2), thus no number after 14 would divide 29 completely, so we can stop here. x = 5, you don't have to check till 4, if 5 is not divisble by 2 (5/2 = 2), no need to check after 2

### CODE REVIEW

**Comment by PratyayDhond** [comment]
@mh31-priyanshu  XD do check this up

**Comment by mh31-priyanshu** [comment]
Thanks for the suggestion @PratyayDhond, it does optimizes the code.
But after reading your code I got and idea to further optimize it - 
instead of dividing by 2 we can use square root of the value, since you can go to sqrt(x)*sqrt(x) but never higher.

e.g.

for 144, for all possibilities of factors of 144 one factor will always be less than than 12 (√144)  so it'll be pointless to try further number more than that.

**Comment by PratyayDhond** [comment]
@mh31-priyanshu I didn't get your approach exactly, for the input 144 it works, but if you test it with the input let's say '10' then sqrt of 10 is 3.34.... which floors down to 3, then the algo will check only till i < 3, and say number is prime, even though it isn't. I think we can't go any further than x/2 in the for loop case

**Comment by mh31-priyanshu** [comment]
@PratyayDhond okay okay, look if we are taking 10 what are the possible factors of it -
1. 5x2
2. 2x5
so in every possibility one of the two operand will be smaller or equal to  3.16...(√10). You can take any number instead of 10.
So as you said for iteration it will check  only till `i <= 3` (where `i = 2`),I guess it'll will be enough to prove it's prime DNA.

**Comment by PratyayDhond** [comment]
cool gotcha @mh31-priyanshu thanks for the correction. Something new I learnt today!! Kudos to this dope repo!

**Pull request merged**
